In [2]:
import numpy as np

In [4]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
list = [1,2,3,4,5]
arr = np.array(list)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.full((5, 2), 3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [9]:
np.random.rand(5, 2)

array([[0.39966682, 0.91666585],
       [0.56327516, 0.08184743],
       [0.35687905, 0.31260261],
       [0.86507777, 0.01126852],
       [0.05659299, 0.48770381]])

In [10]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[35, 95],
       [25, 61],
       [ 5, 21],
       [56, 61],
       [ 5, 57]])

In [11]:
arr + 1 

array([2, 3, 4, 5, 6])

In [12]:
arr > 2

array([False, False,  True,  True,  True])

In [13]:
arr[arr > 2]

array([3, 4, 5])

In [14]:
arr.min()

np.int64(1)